cs_to_mr_dict = {
    "Biomes": "worldgen",
    "Dimensions": "worldgen",
    "Mobs": "mobs",
    "Ores and Resources": "worldgen",
    "Structures": "worldgen",
    "World Gen": "worldgen",
    "Utility & QoL": "utility",
    "Twitch Integration": "twitch",
    "Processing": "technology",
    "Player Transport": "transportation",
    "Genetics": "technology",
    "Farming": "food",
    "Energy, Fluid, and Item Transport": "technology",
    "Energy": "technology",
    "Automation": "technology",
    "Technology": "technology",
    "Storage": "storage",
    "Server Utility": "management",
    "Redstone": "technology",
    "Performance": "optimization",
    "Miscellaneous": "other",
    "MCreator": "mcreator",
    "Map and Information": "utility",
    "Magic": "magic",
    "Food": "food",
    "Education": "education",
    "Cosmetic": "decoration",
    "Bug Fixed": "optimization",
    "Armor, Tools, and Weapons": "equipment",
    "API and Library": "library",
    "Adventure and RPG": "adventure",
    "Addons": "addons",
    "Applied Energistics 2": "technology",
    "Blood Magic": "magic",
    "Buildcraft": "technology",
    "CraftTweaker": "utility",
    "Create": "technology",
    "Forestry": "technology",
    "Galacticraft": "technology",
    "Industrial Craft": "technology",
    "Integrated Dynamics": "technology",
    "KubeJS": "kubejs",
    "Skyblock": "adventure",
    "Thaumcraft": "magic",
    "Thermal Expansion": "technology",
    "Tinker's Construct": "technology",
    "Twilight Forest": "adventure"
}

def curseforge_to_modrinth(word: str) -> str:
    if word in cs_to_mr_dict:
        return cs_to_mr_dict[word]
    else:
        return word